### ISSUE TITLE
need older versions 

### ISSUE THREAD

**Issue by rd1** [pishangujeniya/clipsync-android#5]
clipsync-android v2.0, v1.5 and 1.6 on Android 4.0.4 ICS do not want to install .

the original v1.22 works fine. 

So i'm left to wonder if there is a version between 1.22 and 1.5 that i can use and if it would work with clipsync-windows 3.5 and up?

**Comment by pishangujeniya** [comment]
@rd1  It is not the issue of versions of the Android app,

Android OS 10 has restricted background reading of ClipBoard of Phone, so this app won't work from Android to Windows Copy Paste, but will work from Windows to Android Copy Paste as usual.

**Comment by rd1** [comment]
who said anything about android 10?

**Comment by pishangujeniya** [comment]
> who said anything about android 10?

Who said there is any version with 1.22?

@rd1

**Comment by rd1** [comment]
you messin with me ?
![Screenshot_2021-02-22-04-28-02](https://user-images.githubusercontent.com/1567489/108689262-de7cce80-74c6-11eb-8757-9c4bcb14595d.png)

**Comment by pishangujeniya** [comment]
@rd1 

You are using this App [https://play.google.com/store/apps/details?id=be.bdwm.clipsync](https://play.google.com/store/apps/details?id=be.bdwm.clipsync)

This is different application.

You are on a different planet

**Comment by rd1** [comment]
fuck off weirdo!
